name: reciclamack_web
description: MVP web client for e-waste educational detection.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  http_parser: ^4.1.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/fallback/roboto/v32/KFOmCnqEu92Fr1Me4GZLCzYlKw.woff2
    - assets/fonts/fallback/notosanssymbols/v43/rP2up3q65FkAtHfwd-eIS2brbDN6gxP34F9jRRCe4W3gfQ8gb_VFRkzrbQ.woff2
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-ExtraBold.ttf
          weight: 800
